[package]
name = "subsonic"
version.workspace = true
edition = "2024"

[dependencies]
axum.workspace = true
client = { path = "../client" }
iroh.workspace = true
iroh-tickets.workspace = true
md5.workspace = true
protocol = { path = "../protocol" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url = "2"

[lib]
path = "src/lib.rs"

[[bin]]
name = "iroh-fm-subsonic"
path = "src/main.rs"
