[package]
name = "iroh-fm-android-native"
version.workspace = true
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22"
client = { path = "../client" }
iroh.workspace = true
iroh-dns = "1.0.3"
iroh-tickets.workspace = true
jni = "0.21"
protocol = { path = "../protocol" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
