[package]
name = "iroh-fm-android-native"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
client = { path = "../client" }
iroh.workspace = true
iroh-tickets.workspace = true
jni = "0.21"
protocol = { path = "../protocol" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
